// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB6FUSeC2eLtr8UYFTb3jH_aAT73MnUY40',
    appId: '1:477110264934:web:c55b8be672b2be5d75f9a7',
    messagingSenderId: '477110264934',
    projectId: 'portfolio-9d8ff',
    authDomain: 'portfolio-9d8ff.firebaseapp.com',
    storageBucket: 'portfolio-9d8ff.appspot.com',
    measurementId: 'G-WR3C550LH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRIJGMAzezfhYrPg8V1CNxRIl29sSJqbc',
    appId: '1:477110264934:android:8a301a5de82d38b875f9a7',
    messagingSenderId: '477110264934',
    projectId: 'portfolio-9d8ff',
    storageBucket: 'portfolio-9d8ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbPh342D9gcBOhIiimKvJZP8dwUsdNBAk',
    appId: '1:477110264934:ios:f8ef2890458a5b5a75f9a7',
    messagingSenderId: '477110264934',
    projectId: 'portfolio-9d8ff',
    storageBucket: 'portfolio-9d8ff.appspot.com',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbPh342D9gcBOhIiimKvJZP8dwUsdNBAk',
    appId: '1:477110264934:ios:f8ef2890458a5b5a75f9a7',
    messagingSenderId: '477110264934',
    projectId: 'portfolio-9d8ff',
    storageBucket: 'portfolio-9d8ff.appspot.com',
    iosBundleId: 'com.example.myPortfolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB6FUSeC2eLtr8UYFTb3jH_aAT73MnUY40',
    appId: '1:477110264934:web:78b5df5d45b6afa975f9a7',
    messagingSenderId: '477110264934',
    projectId: 'portfolio-9d8ff',
    authDomain: 'portfolio-9d8ff.firebaseapp.com',
    storageBucket: 'portfolio-9d8ff.appspot.com',
    measurementId: 'G-ST45W753Y0',
  );
}
